# Generated by Django 6.0.3 on 2026-03-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('team_size', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('workspace_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
