# Generated by Django 6.0.3 on 2026-04-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_companylead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
