# Generated by Django 6.0.3 on 2026-04-14 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_businessenterpriselead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('special_id', models.IntegerField(blank=True, null=True)),
                ('issue_type', models.CharField(choices=[('booking', 'Booking Issue'), ('payment', 'Payment Issue'), ('account', 'Account Issue'), ('refund', 'Refund Issue'), ('availability', 'Availability'), ('pricing', 'Pricing Issue'), ('technical', 'Technical Issue'), ('cancel', 'Cancel Booking'), ('modify', 'Modify Booking'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('admin_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
