# Generated by Django 6.0.3 on 2026-04-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModernLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
