# Generated by Django 6.0.3 on 2026-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_modernlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
