# Generated by Django 6.0.3 on 2026-05-05 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_companylead_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylead',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
