# Generated by Django 6.0.3 on 2026-05-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_companylead_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadss',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
