# Generated by Django 6.0.3 on 2026-05-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_leadss_preferred_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadss',
            name='preferred_location',
        ),
    ]
