# Generated by Django 6.0.3 on 2026-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_modernlead_preferred_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadss',
            name='offer_workspace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leadss',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
