# Generated by Django 6.0.3 on 2026-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_leadss_offer_workspace_leadss_preferred_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylead',
            name='workspace_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companylead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
