# Generated by Django 6.0.3 on 2026-05-11 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_companylead_workspace_type_alter_companylead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('workspace_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('team_size', models.CharField(max_length=50)),
                ('total_price', models.IntegerField(default=0)),
                ('quotation_pdf', models.FileField(blank=True, null=True, upload_to='quotation_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
