# Generated by Django 6.0.3 on 2026-05-11 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_quotationlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationlead',
            name='location',
        ),
        migrations.RemoveField(
            model_name='quotationlead',
            name='quotation_pdf',
        ),
        migrations.RemoveField(
            model_name='quotationlead',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='quotationlead',
            name='total_price',
        ),
        migrations.AddField(
            model_name='quotationlead',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='quotationlead',
            name='preferred_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationlead',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationlead',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='quotationlead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotationlead',
            name='workspace_type',
            field=models.CharField(max_length=120),
        ),
    ]
