# Generated by Django 6.0.3 on 2026-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_remove_quotationlead_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlead',
            name='quotation_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
