# Generated by Django 6.0.3 on 2026-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_quotationlead_quotation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
