# Generated by Django 6.0.3 on 2026-05-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_quotationlead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadss',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadss',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leadss',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leadss',
            name='final_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
