# Generated by Django 6.0.3 on 2026-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_otp_verified_profile_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('Hitech City', 'Hitech City'), ('Madhapur', 'Madhapur'), ('Gachibowli', 'Gachibowli'), ('Kondapur', 'Kondapur'), ('Financial District', 'Financial District')], max_length=100, null=True),
        ),
    ]
