# Generated by Django 6.0.3 on 2026-03-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
