# Generated by Django 6.0.3 on 2026-04-14 09:07

import bookings.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_owner_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='expires_at',
            field=models.DateTimeField(default=bookings.models.cart_expiry),
        ),
    ]
