# Generated by Django 6.0.3 on 2026-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_cartitem_created_at_cartitem_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PAID', max_length=50),
        ),
    ]
