# Generated by Django 6.0.3 on 2026-04-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_payment_id_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.IntegerField(default=0),
        ),
    ]
