# Generated by Django 6.0.3 on 2026-04-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_refund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
