# Generated by Django 6.0.3 on 2026-04-23 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_cancelrequest'),
        ('workspaces', '0007_remove_workspace_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('FULL_DAY', 'Full Day')], max_length=20)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField(default=50)),
                ('booked_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.slot'),
        ),
    ]
