# Generated by Django 6.0.3 on 2026-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
