# Generated by Django 6.0.3 on 2026-03-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('day_pass', 'Day Pass'), ('meeting', 'Meeting Rooms'), ('fixed', 'Fixed Seats'), ('cabin', 'Cabins')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('hourly_price', models.IntegerField()),
                ('daily_price', models.IntegerField()),
                ('monthly_price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
