# Generated by Django 6.0.3 on 2026-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
