# Generated by Django 6.0.3 on 2026-04-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_workspace_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='is_available',
        ),
    ]
