# Generated by Django 6.0.3 on 2026-04-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_remove_workspace_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('FULLDAY', 'Full Day')], default='HOURLY', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField(default=50)),
                ('booked_count', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='workspaces.workspace')),
            ],
        ),
    ]
