# Generated by Django 6.0.3 on 2026-04-23 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspaceslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workspaceslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='workspaceslot',
            name='end_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceslot',
            name='start_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspaceslot',
            name='slot_type',
            field=models.CharField(choices=[('hour', 'Hourly'), ('day', 'Full Day')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workspaceslot',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
