# Generated by Django 6.0.3 on 2026-04-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_remove_workspaceslot_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspaceslot',
            old_name='end_hour',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='workspaceslot',
            old_name='start_hour',
            new_name='start_time',
        ),
    ]
