# Generated by Django 6.0.3 on 2026-04-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_rename_end_hour_workspaceslot_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceslot',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='workspaces.workspace'),
        ),
    ]
