# Generated by Django 6.0.3 on 2026-04-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_alter_workspaceslot_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('wifi', 'WiFi'), ('coffee', 'Coffee'), ('24hr', '24 Hour Open'), ('security', 'Security'), ('firewall', 'Firewall'), ('parking', 'Parking'), ('meeting', 'Meeting Room'), ('games', 'Games'), ('pantry', 'Pantry'), ('cleaning', 'House Keeping'), ('support', 'Customer Support')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='workspaces.amenity'),
        ),
    ]
