# Generated by Django 6.0.3 on 2026-04-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_amenity_workspace_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='custom_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, choices=[('wifi', 'WiFi 📶'), ('coffee', 'Coffee ☕'), ('24hr', '24 Hour ⏰'), ('security', 'Security 🛡️'), ('parking', 'Parking 🅿️'), ('meeting', 'Meeting 🏢'), ('games', 'Games 🎮'), ('pantry', 'Pantry 🍽️'), ('cleaning', 'Cleaning 🧹'), ('support', 'Support 💬'), ('ac', 'AC ❄️'), ('printer', 'Printer 🖨️'), ('locker', 'Locker 🔐'), ('lounge', 'Lounge 🛋️'), ('elevator', 'Elevator 🛗'), ('reception', 'Reception 🧑\u200d💼'), ('conference', 'Conference 📊'), ('snacks', 'Snacks 🍪'), ('water', 'Water 🚰'), ('charging', 'Charging 🔌'), ('cctv', 'CCTV 📹')], max_length=50),
        ),
    ]
