# Generated by Django 6.0.3 on 2026-05-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_monthlyslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
