# Generated by Django 6.0.3 on 2026-05-06 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_workspace_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('original_price', models.IntegerField()),
                ('offer_price', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('floor', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
