# Generated by Django 6.0.3 on 2026-05-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_additionalamenity_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='isavailable',
            field=models.BooleanField(default=True),
        ),
    ]
