# Generated by Django 6.0.3 on 2026-05-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0023_workspace_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerworkspace',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_workspaces', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='offerworkspace',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
