# Generated by Django 6.0.3 on 2026-03-26 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefers_quiet', models.BooleanField(default=False)),
                ('prefers_window', models.BooleanField(default=False)),
                ('prefers_ac', models.BooleanField(default=True)),
                ('budget', models.FloatField(default=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('is_quiet', models.BooleanField(default=False)),
                ('is_window', models.BooleanField(default=False)),
                ('is_near_ac', models.BooleanField(default=False)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aibased.workspace')),
            ],
        ),
    ]
