# Generated by Django 6.0.3 on 2026-03-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aibased', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
