# Generated by Django 6.0.3 on 2026-03-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aibased', '0004_remove_userpreference_user_delete_seat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('workspace_type', models.CharField(choices=[('coworking', 'Coworking'), ('private', 'Private Office'), ('meeting', 'Meeting Room')], max_length=20)),
                ('amenities', models.JSONField()),
                ('capacity', models.IntegerField()),
                ('image', models.URLField()),
            ],
        ),
    ]
